### ISSUE TITLE
facing errors in github sarif upload for GHAS

### ISSUE THREAD

**Issue by amitgupta7** [SvanBoxel/zaproxy-to-ghas#37]
GHAS Sarif upload errors out with the SARF [ZAProxy-sarif-report (2).zip](https://github.com/SvanBoxel/zaproxy-to-ghas/files/8146793/ZAProxy-sarif-report.2.zip) configured [in this workflow](https://github.com/amitgupta7/jstest/blob/7ea35de8a232feb06f9574bdcf39a2db4e905f30/.github/workflows/dast-run.yml)
```
 - name: Run a multi-line script
        run: |
          echo "::debug::`ls`" &
          nohup python3 -m http.server & 
          sleep 5 
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: 'http://localhost:8000/' # Target url for the scan
          cmd_options: '-a'
      - name: Create sarif file from zaproxy results
        uses: SvanBoxel/zaproxy-to-ghas@main
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
          # the sarif processing errors out, hence wait for processing
          wait-for-processing: true 
```

I think the `localhost:8000` string is breaking sarif compatibility. Please see the error below:
```
Error: Code Scanning could not process the submitted SARIF file:
[18](https://github.com/amitgupta7/jstest/runs/5283129475?check_suite_focus=true#step:6:18)
  SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,
[19](https://github.com/amitgupta7/jstest/runs/5283129475?check_suite_focus=true#step:6:19)
  Error: Code Scanning could not process the submitted SARIF file:
[20](https://github.com/amitgupta7/jstest/runs/5283129475?check_suite_focus=true#step:6:20)
  SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,SARIF URI scheme “localhost” did not match the checkout URI scheme “file”,
[21](https://github.com/amitgupta7/jstest/runs/5283129475?check_suite_focus=true#step:6:21)
      at Object.waitForProcessing (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:323:23)
[22](https://github.com/amitgupta7/jstest/runs/5283129475?check_suite_focus=true#step:6:22)
      at async run (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:53:13)
[20](https://github.com/amitgupta7/jstest/runs/5283129475?check_suite_focus=true#step:6:20)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:68:9)
```
